// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {},
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/policy": {
            "post": {
                "description": "Creates a new policy for applying rules to a project",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Policy"
                ],
                "summary": "Create policy",
                "parameters": [
                    {
                        "description": "Policy input",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_hse-revizor_rules-service_internal_pkg_router_dto.CreatePolicyDto"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_hse-revizor_rules-service_internal_pkg_router_dto.GetPolicyDto"
                        }
                    }
                }
            }
        },
        "/policy/{id}": {
            "get": {
                "description": "Returns policy model with provided id",
                "tags": [
                    "Policy"
                ],
                "summary": "Get policy by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Policy id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_hse-revizor_rules-service_internal_pkg_router_dto.GetPolicyDto"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes policy with provided id",
                "tags": [
                    "Policy"
                ],
                "summary": "Delete policy by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Policy id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_hse-revizor_rules-service_internal_pkg_router_dto.GetPolicyDto"
                        }
                    }
                }
            }
        },
        "/rule/{id}": {
            "get": {
                "description": "In success case returns rule model with provided id",
                "tags": [
                    "Rule"
                ],
                "summary": "Get rule by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Rule id input",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": " "
                    }
                }
            },
            "delete": {
                "description": "In success case delete rule model with provided id",
                "tags": [
                    "Rule"
                ],
                "summary": "Delete rule by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Rule id input",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": " "
                    }
                }
            }
        },
        "/rules": {
            "post": {
                "description": "In success case returns created rule model. Type must be equal (HasFile, HasStringInFile, HasExpectedValueInField, StrictEquality, HasSubstring, HasRegexMatch, NoSubstring, NotLongerThan, NotShorterThan, NotEmpty, DoesLLMSayThatRuleIsSatisfied)",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Rule"
                ],
                "summary": "Create rule",
                "parameters": [
                    {
                        "description": "Rule input",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_hse-revizor_rules-service_internal_pkg_router_dto.CreateRuleDto"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": " "
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_hse-revizor_rules-service_internal_pkg_router_dto.CreatePolicyDto": {
            "type": "object",
            "required": [
                "projectId",
                "rulesIds"
            ],
            "properties": {
                "projectId": {
                    "type": "string"
                },
                "rulesIds": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "github_com_hse-revizor_rules-service_internal_pkg_router_dto.CreateRuleDto": {
            "type": "object",
            "required": [
                "params",
                "typeId"
            ],
            "properties": {
                "params": {
                    "type": "string"
                },
                "typeId": {
                    "type": "string"
                }
            }
        },
        "github_com_hse-revizor_rules-service_internal_pkg_router_dto.GetPolicyDto": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "projectId": {
                    "type": "string"
                },
                "rulesIds": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Rules Service API",
	Description:      "This is a Swagger documentation.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
